### ISSUE TITLE
Select all checkbox in multi select table

### ISSUE THREAD

**Issue by dhananjaysakhare244** [scania-digital-design-system/tegel-react-demo#173]
when I run tegel react demo library (https://www.npmjs.com/package/@scania/tegel-react) I get different behavior in Table.
When I Click on select all checkbox for first time it check all other checkboxes
When I try to deselect it sometimes works perfectly but sometimes it is still checked

**Comment by theJohnnyMe** [comment]
Issue is fixed and PR is merged ;)
